server:
  port: 9000
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
  redis:
    database: 1
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: 10000
        min-idle: 3
    password: 123456
    port: 6379
    timeout: 50000
