server:
  port: 8120
spring:
  redis:
    database: 1
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: 10000
        min-idle: 3
    password:
    port: 6379
    timeout: 50000